admin_crud:
    resource: "@AdminBundle/Controller/"
    type:     annotation

fos_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile