<?php

namespace AppBundle\Repository;

/**
 * CharityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharityCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
