<?php

namespace AppBundle\Repository;

/**
 * CharityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharityRepository extends \Doctrine\ORM\EntityRepository
{
}
