<?php

namespace AppBundle\Repository;

/**
 * CommunityQuestionAnswerVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityQuestionAnswerVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
