<?php

namespace AppBundle\Repository;

/**
 * CommunityCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
