<?php

namespace AppBundle\Repository;

/**
 * CommunityQuestionVoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommunityQuestionVoteRepository extends \Doctrine\ORM\EntityRepository
{
}
