<?php

namespace AppBundle\Repository;

/**
 * GoalCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalCategoryRepository extends \Doctrine\ORM\EntityRepository
{
}
