<?php

namespace AppBundle\Repository;

/**
 * GoalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function count()
    {
        return $this->_em->createQuery('SELECT COUNT(g.id) FROM AppBundle\Entity\Goal g WHERE g.predefined = true AND g.originGoal IS NULL')->getSingleScalarResult();
    }

	/**
	 * @return array
	 */
    public function findPredifined()
    {
        return $this->_em->createQueryBuilder()->select('g')
            ->from('AppBundle:Goal', 'g')
//            ->where('g.deadline IS NULL')
	        ->where('g.predefined = true')
	        ->andWhere('g.originGoal IS NULL')
            ->getQuery()->getResult();
    }
}
