<?php

namespace AppBundle\Repository;

/**
 * GoalGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GoalGroupRepository extends \Doctrine\ORM\EntityRepository
{
}
