<?php

namespace AppBundle\Repository;

/**
 * GroupInviteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupInviteRepository extends \Doctrine\ORM\EntityRepository
{
}
