<?php

namespace AppBundle\Repository;

use UserBundle\Entity\User;

/**
 * GroupUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GroupUserRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param $groupUserId
     * @param User $user
     * @return \Doctrine\ORM\QueryBuilder
     */
    public function findGroupUserGoal($groupUserId, User $user)
    {
        return $this->getEntityManager()->createQueryBuilder()
            ->select('g')->from('AppBundle:GroupUser', 'g')
            ->where('g.id = :groupUserId')
            ->andWhere('g.user = :user')
            ->setParameter('groupUserId', $groupUserId)
            ->setParameter('user', $user)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
