<?php

namespace AppBundle\Repository;

/**
 * PaymentChargeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaymentChargeRepository extends \Doctrine\ORM\EntityRepository
{
}
