<?php

namespace AppBundle\Repository;


use AppBundle\Entity\SupervisorCheckinTokens;

/**
 * SupervisorCheckinTokensRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupervisorCheckinTokensRepository extends \Doctrine\ORM\EntityRepository
{
	public function findApprovals()
	{
		return $this->_em->createQueryBuilder()
			->select('s')
			->from('AppBundle:SupervisorCheckinTokens', 's')
			->where('s.status =:mailStatus')
			->andwhere('s.mailAttemps < 3')
			->setParameter('mailStatus', SupervisorCheckinTokens::MAIL_OPEN)->getQuery()->getResult();
	}

	/**
	 * @param $userGoalId
	 * @return int
	 */
	public function countOpenSupervisorApprovals($userGoalId)
	{
		return (int) $this->_em->createQuery('
			SELECT COUNT(s.id) FROM AppBundle\Entity\SupervisorCheckinTokens s WHERE s.userGoal = :userGoal
			')->setParameter('userGoal', $userGoalId)
			->getSingleScalarResult();
	}

	/**
	 * @param $userGoalId
	 * @return int
	 */
	public function getLastSupervisorApprovalDate($userGoalId)
	{
		$result =  $this->_em->createQuery('
			SELECT s.createdAt FROM AppBundle\Entity\SupervisorCheckinTokens s WHERE s.userGoal = :userGoal ORDER BY s.id DESC
			')->setParameter('userGoal', $userGoalId)
			->setMaxResults(1)->getOneOrNullResult();

		if ($result){
			return $result['createdAt'];
		}

		return false;
	}
}
