<?php

namespace AppBundle\Repository;

/**
 * UserGoalImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGoalImageRepository extends \Doctrine\ORM\EntityRepository
{

	/**
	 * @param $userGoalId
	 * @return int
	 */
	public function countNotSendedEmbarrassingImages($userGoalId)
	{
		return (int) $this->_em->createQuery('
			SELECT COUNT(u.id) FROM AppBundle\Entity\UserGoalImage u WHERE u.userGoal = :userGoalId AND u.mailSended = false
			')->setParameter('userGoalId', $userGoalId)
			->getSingleScalarResult();
	}

	public function updateAllSendedEmbarrassingImages($userGoalId)
	{
		return $this->_em->createQuery('
			UPDATE AppBundle\Entity\UserGoalImage u SET u.mailSended = true, u.mailAttemps = +1 WHERE u.userGoal =  :userGoalId
		')->setParameter('userGoalId', $userGoalId)->getScalarResult();
	}
}
