<?php

namespace AppBundle\Repository;

/**
 * UserGoalCharityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserGoalCharityRepository extends \Doctrine\ORM\EntityRepository
{
}
